django_app/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

# HttpResponse / HttpRequest를 위한 url
from post.urls import views as post_urls
from post.urls import apis as post_apis_urls
from member.urls import apis as member_apis_urls

api_urlpatterns = [
    url(r'^post/', include(post_apis_urls)),
    url(r'^member/', include(member_apis_urls)),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include(post_urls)),
    url(r'^api/', include(api_urlpatterns, namespace='api')),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

django_app/post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^create/$', views.post_create, name='post-create'),
    url(r'^photo/add/$', views.post_photo_add, name='photo_add'),
]

django_app/post/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-pk',)


class PostPhoto(models.Model):
    post = models.ForeignKey(Post)
    photo = models.ImageField(upload_to='post')
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        order_with_respect_to = 'post'

        # def to_dict(self):
        #     ret = {
        #         'pk': self.pk,
        #         'photo': self.photo.url,
        #     }
        #     return ret

django_app/post/models/comment.py
from django.db import models

from config import settings
from post.models.post import Post

__all__ = (
    'PostComment',
)


class PostComment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()

    def __str__(self):
        return '{} comment (author: {})'.format(
            self.post_id,
            self.author_id,
        )

django_app/post/models/post.py
from django.conf import settings
from django.db import models

__all__ = (
    'Post',
    'PostPhoto',
)


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-pk',)


class PostPhoto(models.Model):
    post = models.ForeignKey(Post)
    photo = models.ImageField(upload_to='post')
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        order_with_respect_to = 'post'

        # def to_dict(self):
        #     ret = {
        #         'pk': self.pk,
        #         'photo': self.photo.url,
        #     }
        #     return ret

django_app/post/forms.py
from django import forms


class PostForm(forms.Form):
    content = forms.CharField(required=False)
    photos = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'multiple': True,
            }
        )
    )

django_app/post/urls/views.py
from django.conf.urls import url

from .. import views

app_name = 'post'
urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='post-list'),
    url(r'^(?P<pk>[0-9]+)/$', views.PostDetail.as_view(), name='post-detail'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.PostDelete.as_view(),
        name='post-delete'),
    url(r'^create/$', views.PostCreate.as_view(), name='post-create'),
    url(r'^(?P<post_pk>[0-9]+)/comment/create/$',
        views.CommentCreate.as_view(),
        name='comment-create'),
    # url(r'^post-list/$', views.post_list, name='post-list'),
    # url(r'^create/$', views.post_create, name='post-create'),
    # url(r'^photo/add/$', views.post_photo_add, name='photo_add'),
]

django_app/post/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from .models import Post, PostPhoto

User = get_user_model()


@csrf_exempt
def post_list(request):
    context = {
        'post_list': [post.to_dict() for post in
                      Post.objects.select_related('author')],
    }
    return JsonResponse(data=context)


@csrf_exempt
def post_create(request):
    """
    request.POST로 전달된 author_id를 받아서 새 post를 생성
    이후 생성된 post의 id값을 HttpResponse로 반환

    받은 author_id에 해당하는 MyUser객체를 가져옴
    실패시 예외처리로 주어진 author_id 에 해당하는 User는 없음을 리턴
    """
    if request.method == 'POST':
        try:
            author_id = request.POST['author_id']
            author = User.objects.get(id=author_id)
        except KeyError:
            return HttpResponse('key "author_id" is required field', status=403)
        except User.DoesNotExist:
            return HttpResponse('author_id {} is not exist'.format(
                request.POST['author_id']))

        post = Post.objects.create(author=author)
        return HttpResponse('{}'.format(post.pk))
    else:
        return HttpResponse('Post create view')


@csrf_exempt
def post_photo_add(request):
    """
    post_id, photo를 받아서
    PostPhoto객체를 생성
    이후 post_id와 post에 연결된 photo들의 id값을 리턴
    """
    if request.method == 'POST':
        try:
            post_id = request.POST['post_id']
            photo = request.FILES['photo']
            post = Post.objects.get(id=post_id)
        except KeyError:
            return HttpResponse('post_id and photo_id is required fields')
        except Post.DoesNotExist:
            return HttpResponse('post_id {} is not exist'.format(
                request.POST['post_id']
            ))
        PostPhoto.objects.create(
            post=post,
            photo=photo,
        )
        return HttpResponse('Post: {}, Photolist: {}'.format(
            post.id,
            [photo.id for photo in post.postphoto_set.all()]
        ))

django_app/post/views/comment.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView

from post.models.comment import PostComment
from post.models.post import Post

__all__ = (
    'CommentCreate',
)


@method_decorator(login_required, name='dispatch')
class CommentCreate(CreateView):
    """
    Comment Create가 작동할 수 있도록 urls 및 이 뷰를 구현
    """
    model = PostComment
    fields = (
        'content',
    )

    def get_success_url(self):
        next = self.request.GET.get('next')
        return next if next else reverse('post:post-detail',
                                         kwargs={'pk': self.kwargs['post_pk']})

    def form_valid(self, form):
        # author와 post가 빈 PostComment객체 생성
        comment = form.save(commit=False)
        post_pk = self.kwargs['post_pk']
        post = Post.objects.get(pk=post_pk)
        author = self.request.user
        comment.post = post
        comment.author = author
        comment.save()

        return HttpResponseRedirect(self.get_success_url())

django_app/post/views/post.py
"""
- class-based view로
    PostList, PostDetail, PostCreate, PostDelete 뷰를 작성
- 기존 프로젝트의 설정 가져와서 PostList가 작동하도록 구현
    1. settings.py
        STATIC_DIR,, STATICFILES_DIRS 설정
    2. 기존프로젝트의 static폴더 복사
    3. .gitignore에 django_app/static/css/ 추가
    4. 기존 프로젝트의 templates폴더 복사
        TEMPLATE_DIR 변수 설정 TEMPLATE설정의 TEMPLATE_DIRS에 해당 변수 추가
    5. PostList CBV에 get메서드 작성 및 내부 쿼리를 return
"""
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import ListView

from post.forms import PostForm
from post.models.comment import PostComment
from post.models.post import Post, PostPhoto

__all__ = (
    'PostList',
    'PostDetail',
    'PostDelete',
    'PostCreate',
)


class PostList(ListView):
    """
    1. 데이터추가
        Postman으로 Post두개 만들고 각각의 Post에 PostPhoto를 3개 추가
    2. post_list.html에서 posts변수를 loop하며 각 post의 postphoto_set.all을 loop
        postphoto_set을 내부에서 loop하며 내부 loop아이템의 photo.url을 이용해 이미지 출력
    """
    model = Post
    context_object_name = 'posts'


class PostCreate(FormView):
    """
    FormView를 상속받아 구현
    attributes
        template_name
        form_class
        success_url
    method
        form_valid(self, form)
            request는 self.request로 접근 가능
            form.cleaned_data는 바로 사용 가능
            redirect는 정의해줄 필요 없음
    """
    form_class = PostForm
    template_name = 'post/post_create.html'
    success_url = '/post/'

    def form_valid(self, form):
        post = Post.objects.create(author=self.request.user)
        content = form.cleaned_data.get('content').strip()
        if content is not None:
            PostComment.objects.create(
                post=post,
                author=self.request.user,
                content=content,
            )
        photos = self.request.FILES.getlist('photos')
        for photo in photos:
            PostPhoto.objects.create(
                post=post,
                photo=photo,
            )
        return super(PostCreate, self).form_valid(form)

        # form_class = PostForm
        # template_name = 'post/post_create.html'
        #
        # def get(self, request, *args, **kwargs):
        #     form = self.form_class(request.POST)
        #     context = {
        #         'form': form,
        #     }
        #     return render(request, self.template_name, context)
        #
        # def post(self, request, *args, **kwargs):
        #     form = self.form_class(request.POST, request.FILES)
        #     # 해당 request.user를 author로 하는 Post인스턴스 생성
        #     if form.is_valid():
        #         post = Post.objects.create(author=request.user)
        #         # 2. 만약 form.cleaned_data['content']가 빈 값이 아니면 PostComment 인스턴스 생성
        #         content = form.cleaned_data.get('content').strip()
        #         if content is not None:
        #             PostComment.objects.create(
        #                 author=request.user,
        #                 content=content,
        #                 post=post,
        #             )
        #         # 3. request.FILES.getlist('photos')를 loop하며 PostPhoto 인스턴스 생성
        #         photos = request.FILES.getlist('photos')
        #         for photo in photos:
        #             PostPhoto.objects.create(
        #                 post=post,
        #                 photo=photo,
        #             )
        #         # 4. return redirect('post:post-list')
        #         return redirect('post:post-list')
        #     else:
        #         return HttpResponse(form.errors)


class PostDetail(DetailView):
    """
    DetailView를 상속받아서 구현되도록
    """
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['post_list'] = Post.objects.all()
        return context


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('post:post-list')

django_app/templates/post/include/post.html
<article class="post">
    <header class="post-header">
        <span class="header-username">{{ post.author.username }}</span>
        {#                    포스트 삭제를 위한 form#}
        {% if user == post.author %}
{#            <form action="{% url 'post:post-delete' pk=post.pk %}"#}
{#                  method="POST"#}
{#                  class="post_delete">{% csrf_token %}#}
{#                <button type="submit" class="btn">글 삭제</button>#}
{#            </form>#}
            <a href="{% url 'post:post-delete' pk=post.pk %}" class="btn-container">
            <button type="submit" class="btn">글 삭제</button>
            </a>
        {% endif %}
        <span class="header-date">{{ post.created_date }}</span>
    </header>
    <!-- post내부에서 postphoto_set을 루핑하여 postphoto 리스트 작성-->
    <div class="post-image-container">
        <!-- Swiper container -->
        <div class="swiper-container">
            <div class="swiper-wrapper">
                {% for postphoto in post.postphoto_set.all %}
                    <div class="swiper-slide">
                        <a href="{% url 'post:post-detail' pk=post.pk %}">
                            <img src="{{ postphoto.photo.url }}" alt=""
                                 class="post-image">
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- Swiper container end -->
    </div>
    <div class="post-bottom-container">
        {#                    포스트에 컨텐츠가 없이 댓글에만 나오게함#}
        {#                    <div class="post-content">{{ post.content|linebreaksbr|truncatechars:100 }}</div>#}
        <div class="post-like-users">
            {% if post.like_users.all %}
                {% if post.like_count > 1 %}
                    {{ post.like_count }}명이 좋아합니다.
                {% else %}
                    {% for user in post.like_users.all %}
                        <strong>{{ user.username }}</strong>
                        님이 좋아합니다.
                        {#                {% if not forloop.last %}#}
                        {#                    <strong>, </strong>#}
                        {#                {% endif %}#}
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
        <div class="post-comments">
            {% if post.postcomment_set.all %}
                {% for comment in post.postcomment_set.all %}
                    <div class="post-comment">
                        <span class="comment-author">{{ comment.author.username }}</span>
                        <span class="comment-content">{{ comment.content }}</span>
                        {% if user == comment.author %}
                            <form action=""
                                  method="POST"
                                  class="comment_delete">{% csrf_token %}
                                <button type="submit" class="btn">
                                    삭제
                                </button>
                            </form>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="post-comment-form-container" clearfix>
            <form action=""
                  method="POST" class="form-like">{% csrf_token %}
                <button
                        type="submit"
                        class="btn-like
              {% if user in post.like_users.all %}
                sprite-heart-full
              {% else %}
                sprite-heart-empty
              {% endif %}">
                </button>
            </form>
            <form action="{% url 'post:comment-create' post_pk=post.pk %}?next={{ request.path }}"
                  method="POST" class="form-class">{% csrf_token %}
                <input
                        type="text"
                        placeholder="댓글달기"
                        class="input-comment"
                        name="content">
            </form>
        </div>
    </div>
</article>